### ISSUE TITLE
Version compatible

### ISSUE THREAD

**Issue by moubenmao** [saulmm/Android-Material-Examples#3]
It's can't run under 5.0 system.  It's something wrong?

**Comment by saulmm** [comment]
If you take a look to the `build.gradle` file at the `app` module you will se that the `minSdkVersion` is set with the 21 value, that means that only devices will Lollipop are able to run the application.

```javascript
    defaultConfig {
        applicationId "com.saulmm.material.myapplication"
        minSdkVersion 21
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
```

By the way I'm working to support more versions under v21
